/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
import { Player, Team, YourTeamPlayerEvent } from "./types";
export namespace Components {
    interface YatAllNationalTeams {
    }
    interface YatCreateYourTeam {
        /**
          * Prop that retrieves the url param (id of the team)
         */
        "match": MatchResults;
    }
    interface YatHome {
    }
    interface YatNationalTeam {
        /**
          * national team id to retrieve the team from API
         */
        "teamId": number;
    }
    interface YatPlayerCard {
        /**
          * Team name if the team is national
         */
        "nationalTeam"?: string;
        /**
          * Player to display
         */
        "player": Player;
    }
    interface YatRoot {
    }
    interface YatTeam {
        /**
          * Team to display
         */
        "team": Team;
    }
    interface YatYourTeam {
        /**
          * Team to display
         */
        "team": Team;
    }
    interface YatYourTeamPage {
    }
}
declare global {
    interface HTMLYatAllNationalTeamsElement extends Components.YatAllNationalTeams, HTMLStencilElement {
    }
    var HTMLYatAllNationalTeamsElement: {
        prototype: HTMLYatAllNationalTeamsElement;
        new (): HTMLYatAllNationalTeamsElement;
    };
    interface HTMLYatCreateYourTeamElement extends Components.YatCreateYourTeam, HTMLStencilElement {
    }
    var HTMLYatCreateYourTeamElement: {
        prototype: HTMLYatCreateYourTeamElement;
        new (): HTMLYatCreateYourTeamElement;
    };
    interface HTMLYatHomeElement extends Components.YatHome, HTMLStencilElement {
    }
    var HTMLYatHomeElement: {
        prototype: HTMLYatHomeElement;
        new (): HTMLYatHomeElement;
    };
    interface HTMLYatNationalTeamElement extends Components.YatNationalTeam, HTMLStencilElement {
    }
    var HTMLYatNationalTeamElement: {
        prototype: HTMLYatNationalTeamElement;
        new (): HTMLYatNationalTeamElement;
    };
    interface HTMLYatPlayerCardElement extends Components.YatPlayerCard, HTMLStencilElement {
    }
    var HTMLYatPlayerCardElement: {
        prototype: HTMLYatPlayerCardElement;
        new (): HTMLYatPlayerCardElement;
    };
    interface HTMLYatRootElement extends Components.YatRoot, HTMLStencilElement {
    }
    var HTMLYatRootElement: {
        prototype: HTMLYatRootElement;
        new (): HTMLYatRootElement;
    };
    interface HTMLYatTeamElement extends Components.YatTeam, HTMLStencilElement {
    }
    var HTMLYatTeamElement: {
        prototype: HTMLYatTeamElement;
        new (): HTMLYatTeamElement;
    };
    interface HTMLYatYourTeamElement extends Components.YatYourTeam, HTMLStencilElement {
    }
    var HTMLYatYourTeamElement: {
        prototype: HTMLYatYourTeamElement;
        new (): HTMLYatYourTeamElement;
    };
    interface HTMLYatYourTeamPageElement extends Components.YatYourTeamPage, HTMLStencilElement {
    }
    var HTMLYatYourTeamPageElement: {
        prototype: HTMLYatYourTeamPageElement;
        new (): HTMLYatYourTeamPageElement;
    };
    interface HTMLElementTagNameMap {
        "yat-all-national-teams": HTMLYatAllNationalTeamsElement;
        "yat-create-your-team": HTMLYatCreateYourTeamElement;
        "yat-home": HTMLYatHomeElement;
        "yat-national-team": HTMLYatNationalTeamElement;
        "yat-player-card": HTMLYatPlayerCardElement;
        "yat-root": HTMLYatRootElement;
        "yat-team": HTMLYatTeamElement;
        "yat-your-team": HTMLYatYourTeamElement;
        "yat-your-team-page": HTMLYatYourTeamPageElement;
    }
}
declare namespace LocalJSX {
    interface YatAllNationalTeams {
    }
    interface YatCreateYourTeam {
        /**
          * Prop that retrieves the url param (id of the team)
         */
        "match"?: MatchResults;
    }
    interface YatHome {
    }
    interface YatNationalTeam {
        /**
          * national team id to retrieve the team from API
         */
        "teamId"?: number;
    }
    interface YatPlayerCard {
        /**
          * Team name if the team is national
         */
        "nationalTeam"?: string;
        /**
          * Event fired when the user want to remove or add a player to YourTeam
         */
        "onMovePlayerEvent"?: (event: CustomEvent<YourTeamPlayerEvent>) => void;
        /**
          * Player to display
         */
        "player"?: Player;
    }
    interface YatRoot {
    }
    interface YatTeam {
        /**
          * Team to display
         */
        "team"?: Team;
    }
    interface YatYourTeam {
        /**
          * Team to display
         */
        "team"?: Team;
    }
    interface YatYourTeamPage {
    }
    interface IntrinsicElements {
        "yat-all-national-teams": YatAllNationalTeams;
        "yat-create-your-team": YatCreateYourTeam;
        "yat-home": YatHome;
        "yat-national-team": YatNationalTeam;
        "yat-player-card": YatPlayerCard;
        "yat-root": YatRoot;
        "yat-team": YatTeam;
        "yat-your-team": YatYourTeam;
        "yat-your-team-page": YatYourTeamPage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "yat-all-national-teams": LocalJSX.YatAllNationalTeams & JSXBase.HTMLAttributes<HTMLYatAllNationalTeamsElement>;
            "yat-create-your-team": LocalJSX.YatCreateYourTeam & JSXBase.HTMLAttributes<HTMLYatCreateYourTeamElement>;
            "yat-home": LocalJSX.YatHome & JSXBase.HTMLAttributes<HTMLYatHomeElement>;
            "yat-national-team": LocalJSX.YatNationalTeam & JSXBase.HTMLAttributes<HTMLYatNationalTeamElement>;
            "yat-player-card": LocalJSX.YatPlayerCard & JSXBase.HTMLAttributes<HTMLYatPlayerCardElement>;
            "yat-root": LocalJSX.YatRoot & JSXBase.HTMLAttributes<HTMLYatRootElement>;
            "yat-team": LocalJSX.YatTeam & JSXBase.HTMLAttributes<HTMLYatTeamElement>;
            "yat-your-team": LocalJSX.YatYourTeam & JSXBase.HTMLAttributes<HTMLYatYourTeamElement>;
            "yat-your-team-page": LocalJSX.YatYourTeamPage & JSXBase.HTMLAttributes<HTMLYatYourTeamPageElement>;
        }
    }
}
